### ISSUE TITLE
Manual folding?

### ISSUE THREAD

**Issue by UFOMelkor** [vkurdin/idea-php-lambda-folding#1]
Is there any way to fold the closure manually after unfolding it? The only way I actually found is restarting the IDE …

P.S.: Thank you for this great plugin :+1:

**Comment by vkurdin** [comment]
@UFOMelkor, you can use "Fold selection / Remove region" shortcut while cursor positioned on "return" or "function" keywords, i.e., on potentially folded regions:
<img width="802" alt="screen shot 2016-08-14 at 18 24 28" src="https://cloud.githubusercontent.com/assets/136200/17649344/f40f96da-6254-11e6-8576-9890ea005d97.png">

**Comment by UFOMelkor** [comment]
Thank you :+1:
